### ISSUE TITLE
Product Data sheet Tab Set new Design

### ISSUE THREAD

**Issue by hardstonepaul** [Boton-Promo/shopify_theme#4]
![image](https://github.com/user-attachments/assets/48814c3a-ace5-414b-b32d-f016c52b61be)

This Tittle seems like a button yes because is part of a tab set, but while no more tabs don't look good.

Make this design
https://www.figma.com/design/NgWWbeNvXQsKrz7zxwKG9o/Untitled?node-id=0-1&t=gurxKXYDSjjU3k3X-1

**Comment by hardstonepaul** [comment]
Also change the font Family, please.

**Comment by Slaternight** [comment]
Fixed it.

**Comment by hardstonepaul** [comment]
> ![image](https://github.com/user-attachments/assets/48814c3a-ace5-414b-b32d-f016c52b61be)
> 
> This Tittle seems like a button yes because is part of a tab set, but while no more tabs don't look good.
> 
> Make this design https://www.figma.com/design/NgWWbeNvXQsKrz7zxwKG9o/Untitled?node-id=0-1&t=gurxKXYDSjjU3k3X-1

Check new Design!!

**Comment by hardstonepaul** [comment]
![Image](https://github.com/user-attachments/assets/2553395f-bfaf-4627-b52b-6fc0f0c03e90)

@Slaternight make new design.
