### ISSUE TITLE
Newsletter text

### ISSUE THREAD

**Issue by hardstonepaul** [Boton-Promo/shopify_theme#5]
@Slaternight 

Change this text on newsletter modal

![image](https://github.com/user-attachments/assets/d6d04fc9-531e-40f7-a9ed-1e92d155e94b)

Put a relative newsletter text like "¡Suscríbete a nuestro newsletter y descubre ideas únicas para regalos promocionales y productos para el hogar! Sé el primero en conocer nuestras ofertas, novedades y tendencias."

**Comment by Slaternight** [comment]
Done.
![Captura de pantalla 2024-12-05 152527](https://github.com/user-attachments/assets/b185980b-a30b-4eb1-80d2-a603b0e198a9)
